SELECT
	*
FROM (
	SELECT XMLElement("Case",
		XMLAttributes((SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = SCHED_PAT_TYPE_CD) AS "patientType",
			to_char(SCHED_START_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "scheduledStartTime",
			(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = CANCEL_REASON_CD) AS "cancelReason",
			SCHED_DUR AS "duration",
			SURG_CASE_NBR_FORMATTED AS "id",
			SCHED_CLEANUP_DUR AS "turnoverTime",
			(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = SCHED_TYPE_CD) AS "caseType",
			(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = WOUND_CLASS_CD) AS "woundClass",
			(SELECT REPLACE(PRSNL_GROUP_NAME, UNISTR('\0000'), '') FROM PRSNL_GROUP WHERE PRSNL_GROUP_ID = DECODE(SURG_SPECIALTY_ID, 0, 
SCHED_SURG_SPECIALTY_ID, SURG_SPECIALTY_ID)) AS "service",
			to_char(CHECKIN_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "registrationTime",
			(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = ASA_CLASS_CD) AS "asaScore",
			ADD_ON_IND AS "isAddOn",
			to_char(SURG_START_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "firstIncisionTime",
			(SELECT DECODE(pd.REC_VER_ID, 0, 0, 1) FROM PERIOPERATIVE_DOCUMENT pd WHERE pd.SURG_CASE_ID = SURGICAL_CASE.SURG_CASE_ID AND 
pd.DOC_TYPE_CD IN (45065182, 45065477, 49258577)) AS "isFinalized",
			(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = SCHED_SURG_AREA_CD) AS "surgeryArea",
			to_char(CANCEL_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "cancelTime",
			/* ALIASPOOL ECHACCOUNTNUMBER */ (SELECT MAX(ALIAS) FROM ENCNTR_ALIAS ea WHERE ea.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID AND 
ALIAS_POOL_CD = 49211702 AND ACTIVE_IND = 1) AS "acctNum",
			(SELECT REPLACE(NAME_FULL_FORMATTED, UNISTR('\0000'), '') FROM PRSNL WHERE PERSON_ID = SURGEON_PRSNL_ID) AS "surgeon",
			(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = ANESTH_TYPE_CD) AS "anesthesiaType",
			(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = DECODE(SURG_OP_LOC_CD, 0, SCHED_OP_LOC_CD, SURG_OP_LOC_CD)) AS 
"roomName",
			to_char(SURG_STOP_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "lastProcedureCloseTime",
			/* ALIASPOOL ECHMRN */ (SELECT MAX(ALIAS) FROM ENCNTR_ALIAS ea WHERE ea.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID AND 
ALIAS_POOL_CD = 49320274 AND ACTIVE_IND = 1) AS "mrn"),
		
		(SELECT XMLAgg(XMLElement("Allergy",
			XMLAttributes((SELECT SOURCE_STRING FROM NOMENCLATURE WHERE NOMENCLATURE_ID = SUBSTANCE_NOM_ID) AS "name")))
		FROM (ALLERGY) ALLERGY
		WHERE ACTIVE_IND = 1 AND SUBSTANCE_NOM_ID != 0 AND ALLERGY.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID),
		
		(SELECT XMLAgg(XMLElement("Staff",
			XMLAttributes(to_char(IN_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "timeIn",
				to_char(OUT_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "timeOut",
				(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = ROLE_PERF_CD) AS "role",
				(SELECT REPLACE(NAME_FULL_FORMATTED, UNISTR('\0000'), '') FROM PRSNL WHERE PERSON_ID = CASE_ATTENDEE_ID) AS "name",
				CASE_ATTENDEE_ID AS "staffId")))
		FROM (CASE_ATTENDANCE) CASE_ATTENDANCE
		WHERE ACTIVE_IND = 1 AND (SELECT DOC_TYPE_CD FROM PERIOPERATIVE_DOCUMENT pd JOIN SEGMENT_HEADER sh ON pd.PERIOP_DOC_ID = 
sh.PERIOP_DOC_ID WHERE sh.SEGMENT_HEADER_ID = CASE_ATTENDANCE.SEGMENT_HEADER_ID) IN (45065182, 45065477, 49258577) AND 
CASE_ATTENDANCE.SURG_CASE_ID = SURGICAL_CASE.SURG_CASE_ID),
		
		(SELECT XMLAgg(XMLElement("Procedure",
			XMLAttributes((SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = SCHED_ANESTH_TYPE_CD) AS "schedAnesType",
				to_char(PROC_END_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "endTime",
				PROC_TEXT AS "name",
				(SELECT REPLACE(PRSNL_GROUP_NAME, UNISTR('\0000'), '') FROM PRSNL_GROUP WHERE PRSNL_GROUP_ID = DECODE(SURG_SPECIALTY_ID, 0, 
SCHED_SURG_SPECIALTY_ID, SURG_SPECIALTY_ID)) AS "service",
				(DECODE(MODIFIER, NULL, SCHED_MODIFIER, ' ', SCHED_MODIFIER, MODIFIER)) AS "laterality",
				SCHED_SEQ_NUM AS "sortKey",
				(SELECT PRIMARY_MNEMONIC FROM ORDER_CATALOG WHERE CATALOG_CD = DECODE(SURG_PROC_CD, 0, SCHED_SURG_PROC_CD, SURG_PROC_CD)) 
AS "dbName",
				to_char(PROC_START_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "startTime",
				DECODE(PRIMARY_SURGEON_ID, 0, SCHED_PRIMARY_SURGEON_ID, PRIMARY_SURGEON_ID) AS "surgeonId",
				(SELECT REPLACE(NAME_FULL_FORMATTED, UNISTR('\0000'), '') FROM PRSNL WHERE PERSON_ID = DECODE(PRIMARY_SURGEON_ID, 0, 
SCHED_PRIMARY_SURGEON_ID, PRIMARY_SURGEON_ID)) AS "surgeon",
				(DECODE(SURG_PROC_CD, 0, SCHED_PRIMARY_IND, PRIMARY_PROC_IND)) AS "isPrimary",
				SURG_CASE_PROC_ID AS "id")))
		FROM (SURG_CASE_PROCEDURE) SURG_CASE_PROCEDURE
		WHERE ACTIVE_IND = 1 AND SURG_CASE_PROCEDURE.SURG_CASE_ID = SURGICAL_CASE.SURG_CASE_ID),
		
		(SELECT XMLAgg(XMLElement("Patient",
			XMLAttributes(BIRTH_DT_TM AS "dob",
				NAME_LAST AS "lastName",
				NAME_MIDDLE AS "middleName",
				NAME_FIRST AS "firstName",
				(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = SEX_CD) AS "sex")))
		FROM (PERSON) PERSON
		WHERE PERSON.PERSON_ID = SURGICAL_CASE.PERSON_ID),
		
		(SELECT XMLAgg(XMLElement("Event",
			XMLAttributes(to_char(CASE_TIME_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "timestamp",
				(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = TASK_ASSAY_CD) AS "event")))
		FROM (CASE_TIMES) CASE_TIMES
		WHERE ACTIVE_IND = 1 AND CASE_TIMES.SURG_CASE_ID = SURGICAL_CASE.SURG_CASE_ID),
		
		(SELECT XMLAgg(XMLElement("Height",
			XMLAttributes((SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = RESULT_UNITS_CD) AS "heightUnit",
				to_char(VALID_FROM_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "timeDocumented",
				EVENT_TITLE_TEXT AS "name",
				RESULT_VAL AS "height")))
		FROM (CLINICAL_EVENT) HEIGHT
		WHERE EVENT_CD = 2700653 AND RECORD_STATUS_CD = 188 AND REGEXP_LIKE(RESULT_VAL, '^[0-9.]+$') AND 
SYS_EXTRACT_UTC(SYSTIMESTAMP) between VALID_FROM_DT_TM and VALID_UNTIL_DT_TM AND HEIGHT.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID),
		
		(SELECT XMLAgg(XMLElement("Weight",
			XMLAttributes((SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = RESULT_UNITS_CD) AS "weightUnit",
				to_char(VALID_FROM_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "timeDocumented",
				RESULT_VAL AS "weight",
				EVENT_TITLE_TEXT AS "name")))
		FROM (CLINICAL_EVENT) WEIGHT
		WHERE EVENT_CD in (2700654, 21043169, 12933755) AND RECORD_STATUS_CD = 188 AND REGEXP_LIKE(RESULT_VAL, '^[0-9.]+$') AND 
SYS_EXTRACT_UTC(SYSTIMESTAMP) between VALID_FROM_DT_TM and VALID_UNTIL_DT_TM AND WEIGHT.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID),
		
		(SELECT XMLAgg(XMLElement("Tourniquet",
			XMLAttributes(RESULT_VAL AS "value",
				COLLATING_SEQ AS "id",
				EVENT_TITLE_TEXT AS "name",
				to_char(EVENT_START_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "timeDocumented")))
		FROM (CLINICAL_EVENT) TQT
		WHERE EVENT_CD in (3017291, 3017292, 3017293, 3017296) AND RECORD_STATUS_CD = 188 AND SYS_EXTRACT_UTC(SYSTIMESTAMP) between 
VALID_FROM_DT_TM and VALID_UNTIL_DT_TM AND TQT.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID),
		
		(SELECT XMLAgg(XMLElement("Specimens",
			XMLAttributes(RESULT_VAL AS "value",
				COLLATING_SEQ AS "id",
				EVENT_TITLE_TEXT AS "name",
				to_char(EVENT_START_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "timeDocumented")))
		FROM (CLINICAL_EVENT) SPECIMEN
		WHERE EVENT_CD in (3017281, 8888544, 3017284, 8864640) AND RECORD_STATUS_CD = 188 AND SYS_EXTRACT_UTC(SYSTIMESTAMP) between 
VALID_FROM_DT_TM and VALID_UNTIL_DT_TM AND SPECIMEN.ENCNTR_ID = SURGICAL_CASE.ENCNTR_ID),
		
		(SELECT XMLAgg(XMLElement("Drug",
			XMLAttributes(to_char(PERFORMED_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "doseTimestamp",
				(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = RESULT_UNITS_CD) AS "doseUnits",
				RESULT_VAL AS "doseAmount",
				CLINICAL_EVENT_ID AS "id",
				EVENT_TITLE_TEXT AS "name")))
		FROM (CLINICAL_EVENT) DRUG
		WHERE EVENT_CLASS_CD = 232 AND EVENT_TITLE_TEXT != 'IVPARENT' AND EVENT_TITLE_TEXT not like 'Lactated Ringers%' AND 
RECORD_STATUS_CD = 188 AND SYS_EXTRACT_UTC(SYSTIMESTAMP) between VALID_FROM_DT_TM and VALID_UNTIL_DT_TM AND DRUG.ENCNTR_ID = 
SURGICAL_CASE.ENCNTR_ID),
		
		(SELECT XMLAgg(XMLElement("Equipment",
			XMLAttributes(STOCK_NBR AS "stockNumber",
				CLASS_NAME AS "type",
				SHORT_DESC AS "name",
				REQUEST_QTY AS "quantity")))
		FROM ( SELECT SURG_CASE_ID, REQUEST_QTY, cc.ACTIVE_IND, CLASS_NAME, SHORT_DESC, STOCK_NBR FROM CASE_CART_PICK_LIST cc  JOIN 
MM_OMF_ITEM_MASTER mm on mm.ITEM_MASTER_ID = cc.ITEM_ID) EQUIPMENT
		WHERE ACTIVE_IND = 1 AND CLASS_NAME IN ('01 Equipment', '03 Instruments') AND EQUIPMENT.SURG_CASE_ID = 
SURGICAL_CASE.SURG_CASE_ID)).GetClobVal()
	FROM (SURGICAL_CASE) SURGICAL_CASE
	WHERE ACTIVE_IND = 1 AND DEPT_CD = 38626629 AND SCHED_SURG_AREA_CD NOT IN (38624451) AND SCHED_START_DT_TM BETWEEN 
TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP)) - 1 AND TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP)) + 1)