[tool.poetry]
name = "planner-queries"
version = "0.1.0"
description = ""
authors = ["gpeddle <gpeddle@livedata.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlparse = "^0.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
