
SELECT
	*
FROM (
	SELECT XMLElement("FlexString",
		XMLAttributes(SCH_FLEX_ID AS "flexId",
			DESCRIPTION AS "name"),
		
		(SELECT XMLAgg(XMLElement("FlexList",
			XMLAttributes(DOUBLE_VALUE AS "double_value",
				FLEX_TOKEN_MEANING AS "flexToken",
				SEQ_NBR AS "seq",
				(SELECT DESCRIPTION FROM ORDER_ENTRY_FIELDS WHERE OE_FIELD_ID = SCH_FLEX_LIST.OE_FIELD_ID AND SCH_FLEX_LIST.OE_FIELD_ID != 0) AS "oeField",
				PARENT_ID AS "parent_id",
				PARENT_TABLE AS "parentTable",
				OE_FIELD_ID AS "oe_field_id",
				STRING_VALUE AS "string_value"),
			
			(SELECT XMLAgg(XMLElement("Personnel",
				XMLAttributes(USERNAME AS "username",
					/* ALIASPOOL NPI */ (SELECT MAX(ALIAS) FROM (SELECT PRSNL_ALIAS_ID, ALIAS, PERSON_ID as ALIAS_PERSON_ID, ACTIVE_IND, ALIAS_POOL_CD FROM PRSNL_ALIAS) a WHERE ALIAS_PERSON_ID = PERSON_ID AND ALIAS_POOL_CD = {ALIAS_POOL_CD_NPI} AND ACTIVE_IND = 1) AS "npi",
					NAME_FIRST AS "firstName",
					PERSON_ID AS "personId",
					NAME_LAST AS "lastName",
					PHYSICIAN_IND AS "isProvider",
					REPLACE(NAME_FULL_FORMATTED, UNISTR('\0000'), '') AS "fullName",
					ACTIVE_IND AS "isActive")))
			FROM (PRSNL) FLEX_PRSNL
			WHERE SCH_FLEX_LIST.PARENT_TABLE = 'PRSNL' AND FLEX_PRSNL.PERSON_ID = SCH_FLEX_LIST.PARENT_ID),
			
			(SELECT XMLAgg(XMLElement("PersonnelGroup",
				XMLAttributes(to_char(BEG_EFFECTIVE_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "startDate",
					to_char(NULLIF(END_EFFECTIVE_DT_TM, DATE '2100-12-31'), 'yyyy-mm-dd"T"HH24:Mi:ss') AS "endDate",
					PRSNL_GROUP_RELTN_ID AS "prsnlGroupReltnId",
					ACTIVE_IND AS "isActive"),
				
				(SELECT XMLAgg(XMLElement("Personnel",
					XMLAttributes(USERNAME AS "username",
						/* ALIASPOOL NPI */ (SELECT MAX(ALIAS) FROM (SELECT PRSNL_ALIAS_ID, ALIAS, PERSON_ID as ALIAS_PERSON_ID, ACTIVE_IND, ALIAS_POOL_CD FROM PRSNL_ALIAS) a WHERE ALIAS_PERSON_ID = PERSON_ID AND ALIAS_POOL_CD = {ALIAS_POOL_CD_NPI} AND ACTIVE_IND = 1) AS "npi",
						NAME_FIRST AS "firstName",
						PERSON_ID AS "personId",
						NAME_LAST AS "lastName",
						PHYSICIAN_IND AS "isProvider",
						REPLACE(NAME_FULL_FORMATTED, UNISTR('\0000'), '') AS "fullName",
						ACTIVE_IND AS "isActive")))
				FROM (PRSNL) PRSNL
				WHERE PERSON_ID != 0 AND PRSNL.PERSON_ID = PRSNL_GROUP_RELTN.PERSON_ID))
			ORDER BY PRSNL_GROUP_RELTN_ID)
			FROM (PRSNL_GROUP_RELTN) PRSNL_GROUP_RELTN
			WHERE SCH_FLEX_LIST.PARENT_TABLE = 'PRSNL_GROUP' AND PRSNL_GROUP_RELTN.PRSNL_GROUP_ID = SCH_FLEX_LIST.PARENT_ID))
		ORDER BY SEQ_NBR)
		FROM (SCH_FLEX_LIST) SCH_FLEX_LIST
		WHERE FLEX_ORIENT_MEANING = 'POSTFIX' AND SCH_FLEX_LIST.SCH_FLEX_ID = SCH_FLEX_STRING.SCH_FLEX_ID)).GetClobVal()
	FROM (SCH_FLEX_STRING) SCH_FLEX_STRING
	WHERE SCH_FLEX_ID IN ({flexIds})
	ORDER BY DESCRIPTION)