
SELECT
	*
FROM (
	SELECT XMLElement("ApplyList",
		XMLAttributes(APPLY_LIST_ID AS "applyListId",
			SLOT_STATE_MEANING AS "slotState",
			to_char(DEF_BEG_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "def_beg_dt_tm",
			DEF_APPLY_ID AS "defApplyId",
			to_char(BEG_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "startTime",
			to_char(END_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "endTime",
			to_char(DEF_END_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "def_end_dt_tm"),
		
		(SELECT XMLAgg(XMLElement("ApptDef",
			XMLAttributes(SLOT_STATE_MEANING AS "slotState",
				to_char(NULLIF(VIS_END_DT_TM, NULL_DT_TM), 'yyyy-mm-dd"T"HH24:Mi:ss') AS "visibleTo",
				DESCRIPTION AS "description",
				APPLY_DEF_ID AS "apply_def_id",
				NULLIF(SCH_FLEX_ID, 0) AS "flexId",
				to_char(BEG_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "startTime",
				to_char(VIS_BEG_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "visibleFrom",
				APPT_DEF_ID AS "apptDefId",
				to_char(END_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "endTime"))
		ORDER BY VIS_BEG_DT_TM, BEG_DT_TM)
		FROM ( SELECT DISTINCT sa.APPLY_LIST_ID, sa.SLOT_STATE_MEANING, sad.APPLY_DEF_ID, sad.APPT_DEF_ID, sad.SCH_FLEX_ID, sad.BEG_DT_TM, sad.END_DT_TM, sad.VIS_BEG_DT_TM, sad.VIS_END_DT_TM, sad.DESCRIPTION, sad.NULL_DT_TM FROM SCH_APPT_DEF sad JOIN SCH_APPT sa ON sad.APPLY_DEF_ID = sa.APPLY_DEF_ID WHERE sa.SCH_EVENT_ID = 0 OR sa.SLOT_STATE_MEANING = 'ACTIVE' /* we want either available slots (active or not) or active patient appointments */ ) SCH_APPT_DEF
		WHERE SCH_APPT_DEF.APPLY_LIST_ID = SCH_APPLY_LIST.APPLY_LIST_ID),
		
		(SELECT XMLAgg(XMLElement("Action",
			XMLAttributes(to_char(ACTION_DT_TM, 'yyyy-mm-dd"T"HH24:Mi:ss') AS "actionTime",
				SCH_ACTION_ID AS "sch_action_id",
				(SELECT DESCRIPTION FROM APPLICATION_TASK WHERE TASK_NUMBER = SCH_ACTION.UPDT_TASK) AS "description",
				SCH_ACTION_CD AS "sch_action_cd",
				ACTION_MEANING AS "action",
				(SELECT REPLACE(NAME_FULL_FORMATTED, UNISTR('\0000'), '') FROM PRSNL WHERE PERSON_ID = ACTION_PRSNL_ID) AS "action_prsnl"))
		ORDER BY ACTION_DT_TM)
		FROM ( SELECT DISTINCT sa.APPLY_LIST_ID, sac.SCH_ACTION_ID, sac.ACTION_MEANING, sac.SCH_ACTION_CD, sac.ACTION_DT_TM, sac.ACTION_PRSNL_ID, sac.UPDT_TASK FROM SCH_ACTION sac JOIN SCH_APPT sa ON sa.APPLY_SLOT_ID = sac.PARENT_ID AND sac.PARENT_ID2 = 0 AND sac.PARENT_TABLE = 'SCH_APPT' ) SCH_ACTION
		WHERE SCH_ACTION.APPLY_LIST_ID = SCH_APPLY_LIST.APPLY_LIST_ID),
		
		(SELECT XMLAgg(XMLElement("Appt",
			XMLAttributes(STATE_MEANING AS "state_meaning",
				DECODE(SERVICE_RESOURCE_CD, 0, RESOURCE_CD, SERVICE_RESOURCE_CD) AS "roomId",
				SCH_APPT_ID AS "sch_appt_id",
				(SELECT DISPLAY FROM CODE_VALUE WHERE CODE_VALUE = DECODE(SERVICE_RESOURCE_CD, 0, RESOURCE_CD, SERVICE_RESOURCE_CD)) AS "room"),
			
			(SELECT XMLAgg(XMLElement("ScheduleEvent",
				XMLAttributes(SCH_MEANING AS "sch_meaning",
					(SELECT OE_FIELD_DISPLAY_VALUE FROM SCH_EVENT_DETAIL WHERE SCH_EVENT_ID = SCH_EVENT.SCH_EVENT_ID AND OE_FIELD_MEANING = 'REASONFOREXAM' AND VERSION_DT_TM = NULL_DT_TM) AS "reasonForExam",
					SCH_EVENT_ID AS "sch_event_id",
					APPT_SYNONYM_FREE AS "appt_synonym_free")))
			FROM (SCH_EVENT) SCH_EVENT
			WHERE SCH_EVENT_ID != 0 AND SCH_EVENT.SCH_EVENT_ID = SCH_APPT.SCH_EVENT_ID)))
		FROM (SCH_APPT) SCH_APPT
		WHERE ACTIVE_IND = 1 AND SLOT_STATE_MEANING = 'ACTIVE' AND RESOURCE_CD IN (SELECT RESOURCE_CD FROM SCH_BOOK_LIST WHERE APPT_BOOK_ID IN ({APPT_BOOKS})) AND SCH_APPT.APPLY_LIST_ID = SCH_APPLY_LIST.APPLY_LIST_ID)).GetClobVal()
	FROM (SCH_APPLY_LIST) SCH_APPLY_LIST
	WHERE ACTIVE_IND = 1 AND DEF_BEG_DT_TM BETWEEN {startDate} AND {endDate} AND APPLY_LIST_ID IN (SELECT APPLY_LIST_ID FROM SCH_APPT WHERE RESOURCE_CD IN (SELECT RESOURCE_CD FROM SCH_BOOK_LIST WHERE APPT_BOOK_ID IN ({APPT_BOOKS})))
	ORDER BY DEF_BEG_DT_TM)